In [1]:
import numpy as np


In [10]:
a = np.array([1,2,3])

In [11]:
b= np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [13]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,1,2),(4, 6,5)]],dtype=float)

In [15]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.arange(10,25,6)

array([10, 16, 22])

In [25]:
e=np.linspace(0,2,6) 

In [33]:
c=np.array([0 , 0.25, 0.5 , 0.75, 1 , 1.25, 1.5 , 1.75, 2 ])

In [34]:
np.full((2,2) ,7)

array([[7, 7],
       [7, 7]])

In [29]:
x=np.eye(2)

In [30]:
y=np.random.random((2,2))

In [35]:
x

array([[1., 0.],
       [0., 1.]])

In [36]:
y

array([[0.240351  , 0.77248929],
       [0.20966106, 0.93947574]])

In [37]:
np.shape(a)

(3,)

In [38]:
np.shape(b)

(2, 3)

In [39]:
np.shape(c)

(9,)

In [40]:
np.ndim(a)

1

In [41]:
np.ndim(b)

2

In [42]:
np.ndim(c)

1

In [43]:
np.size(a)

3

In [44]:
np.size(b)

6

In [45]:
np.size(c)

9

In [46]:
a.dtype

dtype('int32')

In [47]:
b.dtype

dtype('float64')

In [49]:
c.dtype

dtype('float64')

In [51]:
a.dtype.name

'int32'

In [52]:
b.dtype.name

'float64'

In [53]:
c.dtype.name

'float64'

In [54]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
x=np.multiply(b,b)

In [56]:
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [57]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [59]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [60]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [61]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [62]:
np.sqrt(c)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ,
       1.11803399, 1.22474487, 1.32287566, 1.41421356])

In [63]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [64]:
np.min(a)

np.int32(1)

In [65]:
np.max(a)

np.int32(3)

In [66]:
np.cumsum(a)

array([1, 3, 6])

In [67]:
np.mean(a)

np.float64(2.0)

In [68]:
np.mean(a)

np.float64(2.0)

In [69]:
np.median(a)

np.float64(2.0)

In [70]:
np.std(a)

np.float64(0.816496580927726)